# Generated by Django 4.0.5 on 2022-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
