# Generated by Django 4.0.5 on 2022-06-25 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuid_f',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
