# Generated by Django 4.0.5 on 2022-06-29 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_post_uuid_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid_f',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
