# Generated by Django 4.0.6 on 2022-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_ticket_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_info',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
