# Generated by Django 4.0.6 on 2022-07-22 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_ticket_info_ticket_price_ticket_info_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
