# Generated by Django 4.0.6 on 2022-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_ticket_info_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
