# Generated by Django 4.0.6 on 2022-07-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_ticket_info_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_info',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ticket_info',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket_info',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ticket_info',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='ticket_info',
            name='venue',
        ),
    ]
