# Generated by Django 4.0.6 on 2022-07-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_ticket_info_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
