# Generated by Django 4.0.6 on 2022-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_post_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='money',
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
