# Generated by Django 4.0.6 on 2022-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_post_money_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_info',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
