# Generated by Django 4.0.6 on 2022-07-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_rename_price_ticket_info_ticket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_info',
            old_name='ticket_price',
            new_name='price',
        ),
    ]
