# Generated by Django 4.0.6 on 2022-07-30 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_rename_price_ticket_info_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_info',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
