# Generated by Django 4.0.6 on 2022-07-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_ticket_info_uuid_alter_ticket_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='event_end_time',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='event_organiser',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='event_start_time',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='first_act_time',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='venue',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
