# Generated by Django 4.0.6 on 2022-07-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_ticket_info_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='city',
            field=models.CharField(default='nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='event_end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='event_organiser',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='event_start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='first_act_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
