# Generated by Django 4.0.6 on 2022-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_ticket_info_city_alter_ticket_info_event_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
