# Generated by Django 4.0.6 on 2022-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_website_alter_ticket_info_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
