# Generated by Django 4.0.6 on 2022-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_delete_website_ticket_info_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_info',
            name='event_end_time',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='event_start_time',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='first_act_time',
            field=models.TextField(max_length=100),
        ),
    ]
