# Generated by Django 4.0.6 on 2022-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_ticket_info_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_info',
            name='event_end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='event_start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_info',
            name='first_act_time',
            field=models.CharField(max_length=100),
        ),
    ]
