# Generated by Django 4.0.6 on 2022-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_ticket_info_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
