# Generated by Django 4.0.6 on 2022-08-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_dtmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('made_on', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='DTModel',
        ),
    ]
