# Generated by Django 4.0.6 on 2022-08-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_promise_delete_dtmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_info',
            old_name='date',
            new_name='event_date',
        ),
    ]
