# Generated by Django 4.0.6 on 2022-08-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_remove_ticket_info_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promise',
            old_name='title',
            new_name='ticket_title',
        ),
    ]
