# Generated by Django 4.0.6 on 2022-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_ticket_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
