# Generated by Django 4.0.6 on 2022-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_log_mpesacallbacks_mpesacalls_mpesapayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallStkBacks2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.TextField()),
                ('ResponseCode', models.IntegerField()),
                ('ResponseDescription', models.TextField()),
                ('CustomerMessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MpesaStkCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.TextField()),
                ('ResponseCode', models.IntegerField()),
                ('ResponseDescription', models.TextField()),
                ('CustomerMessage', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call',
                'verbose_name_plural': 'Mpesa Calls',
            },
        ),
        migrations.DeleteModel(
            name='MpesaCallBacks',
        ),
        migrations.DeleteModel(
            name='MpesaCalls',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='updated_at',
        ),
    ]
