# Generated by Django 4.0.6 on 2022-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_rename_mpesastkcalls_mpesapaymentcalls_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='MpesaCallStkBacks2',
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='AccountReference',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='Amount',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='BusinessShortCode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='PartyA',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='PartyB',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='PhoneNumber',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='ResultCode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='ResultDesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='Timestamp',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='TransactionType',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
