# Generated by Django 4.0.6 on 2022-08-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_rename_responsedescription_mpesapaymentcalls_itemamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapaymentcalls',
            old_name='ItemAmount',
            new_name='ItemAmountPaid',
        ),
    ]
