# Generated by Django 4.0.6 on 2022-08-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_rename_itemamount_mpesapaymentcalls_itemamountpaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapaymentcalls',
            old_name='ItemNumber',
            new_name='PhoneNumber2',
        ),
    ]
