# Generated by Django 4.0.6 on 2022-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_mpesapaymentcalls_organiserscut'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='companycut',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
