# Generated by Django 4.0.6 on 2022-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_rename_companycut_mpesapaymentcalls_companycut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapaymentcalls',
            name='Companycut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapaymentcalls',
            name='Organiserscut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
