# Generated by Django 4.0.6 on 2022-09-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_alter_mpesapaymentcalls_companycut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapaymentcalls',
            name='Companycut',
        ),
        migrations.RemoveField(
            model_name='mpesapaymentcalls',
            name='Organiserscut',
        ),
    ]
