# Generated by Django 4.0.6 on 2022-09-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_remove_mpesapaymentcalls_companycut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50)),
            ],
        ),
    ]
