# Generated by Django 4.0.6 on 2022-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_companycut_organisercut'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='CompanyAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='OrganisersAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
