# Generated by Django 4.0.6 on 2022-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_mpesapaymentcalls_companyamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapaymentcalls',
            name='CompanyAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mpesapaymentcalls',
            name='OrganisersAmount',
            field=models.IntegerField(default=0),
        ),
    ]
