# Generated by Django 4.0.6 on 2022-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0066_alter_mpesapaymentcalls_companyamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesareceipt', models.IntegerField()),
                ('ticketname', models.TextField()),
            ],
        ),
    ]
