# Generated by Django 4.0.6 on 2022-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0067_ticketorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='ticketname',
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='mpesareceipt',
            field=models.TextField(),
        ),
    ]
