# Generated by Django 4.0.6 on 2022-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_remove_ticketorder_ticketname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='mpesa_receipt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
