# Generated by Django 4.0.6 on 2022-09-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_mpesapaymentcalls_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapaymentcalls',
            name='mpesa_receipt',
            field=models.CharField(max_length=10000000),
        ),
    ]
