# Generated by Django 4.0.6 on 2022-09-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_alter_mpesapaymentcalls_mpesa_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapaymentcalls',
            name='ticket_no',
            field=models.IntegerField(null=True),
        ),
    ]
