# Generated by Django 4.0.6 on 2022-09-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_alter_mpesapaymentcalls_ticket_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.TextField()),
            ],
        ),
    ]
