# Generated by Django 4.0.6 on 2022-09-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_stkinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapaymentcalls',
            name='ticket_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
