# Generated by Django 4.0.6 on 2022-09-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_mpesapaymentcalls_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapaymentcalls',
            name='ticket_title',
            field=models.CharField(max_length=10000000),
        ),
    ]
