# Generated by Django 4.0.6 on 2022-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0075_alter_mpesapaymentcalls_ticket_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.TextField()),
                ('amount', models.TextField()),
            ],
        ),
    ]
