# Generated by Django 4.0.6 on 2022-09-28 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_alter_b2c_amount_alter_b2c_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
