# Generated by Django 4.0.6 on 2022-09-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_mpesapaymentcalls_event_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapaymentcalls',
            old_name='event_price',
            new_name='Event_price',
        ),
        migrations.RenameField(
            model_name='mpesapaymentcalls',
            old_name='event_title',
            new_name='Event_title',
        ),
        migrations.RenameField(
            model_name='mpesapaymentcalls',
            old_name='withdrawal_code',
            new_name='Withdrawal_code',
        ),
    ]
