# Generated by Django 4.0.6 on 2022-10-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_eventtotals_b2c_withdrawal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtotals',
            old_name='withdrawal_id',
            new_name='Withdrawal_code',
        ),
    ]
