# Generated by Django 4.0.6 on 2022-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0084_rename_withdrawal_id_eventtotals_withdrawal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtotals',
            name='Event_title',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='eventtotals',
            name='Withdrawal_code',
            field=models.CharField(max_length=10000000),
        ),
    ]
