# Generated by Django 4.0.6 on 2022-11-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0088_remove_stkinfo_number_receiving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2c',
            name='B2CChargesPaidAccountAvailableFunds',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='B2CRecipientIsRegisteredCustomer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='B2CUtilityAccountAvailableFunds',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='B2CWorkingAccountAvailableFunds',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ConversationID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ConversationID2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='OriginatorConversationID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='OriginatorConversationID2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ReceiverPartyPublicName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ResponseCode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ResponseDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ResultCode',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ResultDesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='ResultType',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='TransactionAmount',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c',
            name='TransactionReceipt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
