# Generated by Django 4.0.6 on 2022-11-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0089_b2c_b2cchargespaidaccountavailablefunds_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B2C',
            new_name='B2CModel',
        ),
    ]
