# Generated by Django 4.0.6 on 2022-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0090_rename_b2c_b2cmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cmodel',
            name='TransactionID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
