# Generated by Django 4.0.6 on 2022-11-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_b2cmodel_transactionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesapaymentcalls',
            old_name='number_receiving',
            new_name='phone_number',
        ),
    ]
