# Generated by Django 4.0.6 on 2022-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0094_ipmodel_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cmodel',
            name='TransactionCompletedDateTime',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
