# Generated by Django 4.0.6 on 2022-11-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_b2cmodel_transactioncompleteddatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTotals2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipts2', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
