# Generated by Django 4.0.6 on 2022-11-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_eventtotals2_remove_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtotals2',
            name='proceeding',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
