# Generated by Django 4.0.6 on 2022-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0097_eventtotals2_proceeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtotals2',
            name='owner',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
