# Generated by Django 4.0.6 on 2022-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0098_eventtotals2_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtotals2',
            name='CheckoutRequestID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
