# Generated by Django 4.0.6 on 2022-11-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0099_eventtotals2_checkoutrequestid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtotals2',
            old_name='CheckoutRequestID',
            new_name='checkoutRequestID',
        ),
    ]
